name: PracticaDockerYml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkear el repositiorio
        uses: actions/checkout@v2

      - name: Logear a docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Subir microservicio 1
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservicio1:2.0 -f microservicio1/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservicio1:2.0

      - name: Subir microservicio 2
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservicio2:2.0 -f microservicio2/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservicio2:2.0
